INSERT INTO category (name)
VALUES ('Action'),
       ('Comédie'),
       ('Drame'),
       ('Science-Fiction'),
       ('Horreur'),
       ('Thriller'),
       ('Animation'),
       ('Documentaire'),
       ('Fantastique'),
       ('Aventure');

INSERT INTO actor (name, bio)
VALUES ('Tom Hanks',
        'Acteur et producteur américain, connu pour ses rôles dans Forrest Gump, Seul au monde et Il faut sauver le soldat Ryan.'),
       ('Leonardo DiCaprio',
        'Acteur, producteur et écologiste américain. Connu pour ses rôles dans Titanic, Inception et The Revenant.'),
       ('Scarlett Johansson',
        'Actrice et chanteuse américaine. Connue pour son rôle de Black Widow dans l''univers cinématographique Marvel.'),
       ('Denzel Washington',
        'Acteur, réalisateur et producteur américain. Connu pour ses rôles dans Training Day, Malcolm X et American Gangster.'),
       ('Natalie Portman',
        'Actrice, réalisatrice et productrice israélo-américaine. Connue pour ses rôles dans Léon, Black Swan et la saga Star Wars.'),
       ('Morgan Freeman',
        'Acteur, producteur et narrateur américain. Connu pour sa voix grave et ses rôles dans Les Évadés, Seven et Million Dollar Baby.'),
       ('Meryl Streep',
        'Actrice américaine, largement considérée comme l''une des plus grandes actrices de tous les temps. Connue pour Le Choix de Sophie, Le Diable s''habille en Prada et Kramer contre Kramer.'),
       ('Robert De Niro',
        'Acteur, producteur et réalisateur américain. Connu pour ses collaborations avec Martin Scorsese, notamment dans Taxi Driver, Raging Bull et Les Affranchis.'),
       ('Brad Pitt',
        'Acteur et producteur américain. Connu pour ses rôles dans Fight Club, L''Étrange Histoire de Benjamin Button et Once Upon a Time in Hollywood.'),
       ('Angelina Jolie',
        'Actrice, réalisatrice et philanthrope américaine. Connue pour ses rôles dans Lara Croft : Tomb Raider, Mr. & Mrs. Smith et Maléfique.');


INSERT INTO film (title, prod_year, description, release_date, duration, category_id)
VALUES ('Inception', 2010,
        'Un voleur qui dérobe des secrets d''entreprise grâce à la technologie du partage de rêves se voit offrir une chance de rédemption.',
        '2010-07-21', 148, 4),
       ('Forrest Gump', 1994,
        'Les péripéties de la vie de Forrest Gump, un homme simple d''esprit de l''Alabama, dont l''existence est étroitement liée à d''importants événements de l''histoire américaine.',
        '1994-10-05', 142, 3),
       ('The Dark Knight', 2008,
        'Lorsque la menace connue sous le nom du Joker sème la pagaille et le chaos parmi les habitants de Gotham, Batman doit accepter l''un de ses plus grands défis psychologiques et physiques afin de combattre l''injustice.',
        '2008-08-13', 152, 1),
       ('Pulp Fiction', 1994,
        'Les vies de deux tueurs à gages, d''un boxeur, de la femme d''un gangster et de deux braqueurs de diner s''entremêlent dans quatre histoires de violence et de rédemption.',
        '1994-10-26', 154, 6),
       ('Le Seigneur des Anneaux : Le Retour du Roi', 2003,
        'Gandalf et Aragorn mènent le Monde des Hommes contre l''armée de Sauron pour détourner son regard de Frodon et Sam qui approchent du Mont du Destin avec l''Anneau Unique.',
        '2003-12-17', 201, 9),
       ('Gladiator', 2000,
        'Un général romain trahi et sa famille assassinée par l''empereur Commode, devient gladiateur dans l''espoir d''assouvir sa vengeance.',
        '2000-06-20', 155, 1),
       ('Titanic', 1997,
        'Un aristocrate de dix-sept ans tombe amoureuse d''un artiste pauvre mais gentil à bord du luxueux et malheureux R.M.S. Titanic.',
        '1998-01-07', 195, 3),
       ('Le Silence des Agneaux', 1991,
        'Une jeune recrue du FBI doit faire confiance à un tueur en série manipulateur et incarcéré pour l''aider à appréhender un autre tueur en série, un dément qui écorche ses victimes.',
        '1991-04-10', 118, 6),
       ('Matrix', 1999,
        'Un pirate informatique apprend de mystérieux rebelles la vraie nature de sa réalité et son rôle dans la guerre contre ceux qui la contrôlent.',
        '1999-06-23', 136, 4),
       ('La Vie est Belle', 1997,
        'Quand un bibliothécaire juif à l''esprit ouvert et son fils deviennent victimes de l''Holocauste, il utilise un mélange parfait de volonté, d''humour et d''imagination pour protéger son fils des dangers de leur camp.',
        '1998-10-21', 116, 2);

INSERT INTO film_actor (film_id, actor_id)
VALUES (1, 2),
       (2, 1),
       (3, 4),
       (4, 3),
       (5, 6),
       (6, 4),
       (7, 2),
       (8, 5),
       (9, 2),
       (10, 8);
